title: The Gerhardt Hymnal
author: Ian M. Welch 
description: Paul Gerhardt's hymns and information about them.
url: gerhardthymnal.com

nordic:
  date_format: "%B %-d, %Y"

# Nav Options
reverse: false

exclude:
  - .jekyll-cache